training:
  batch_size: 16                           # Tran/val/test batch size
  lr: 1.0e-4                                # Learning rate
  epochs: 5                                 # Training epochs
  weight_decay: 1.0e-4                      # Weight decay
  optimizer: "AdamW"                        # Optimizer

loss:
  loss_fun: "DensityCountLoss"              # Loss function
  loss_args: 
    lbda_count: 2                         # Count loss weight

target_map:
  target_map_fun: "generate_density_map"    # Function id to create target map
  target_map_args: 
    sigma: 10                               # Target density map standard deviation
  use_blend_maps: true                     # If true, pregenerated target maps are used

model:
  model_name: "model0_densitycount10"             # Model name
  model_type: "densitycount-model"               # Type of model
  activation: "ReLUTanh"                    # Last layer activation
  # Transfer learning (ignored when resuming an existing model_name or pre_model_name = null)
  pre_model_name: null #"model0_density10"        # null = no transfer learning
  pre_cp: "best"                            # "last" = last checkpoint; "best" = best checkpoint
  
transforms:
  short_side: 512                           # Short side len of transformed image
  brightness: 0.2                           # Random brightness scale parameter
  imagenet_normalization: false              # false for models not pretrained on ImageNet

paths:
  train_data: "data/preprocessed/train"     # Path to training data
  val_data: "data/preprocessed/val"         # Path to validation data
  test_data: "data/preprocessed/test"       # Path to testing data
  models: "models"                          # Path to models
  outputs: "outputs"                        # Path to eval outputs
